#!/usr/bin/env python3
"""How much size sits at each price a sweep counts — the measurement behind
SWEEP_LEVEL_MIN_SIZE / SWEEP_LEVEL_MIN_SHARE. [st-r6ni]

Steve, 2026-08-21: "7685.00 to 7685.5 is not across 3 prices." 481 of 538
contracts went off at one price; the tail carried 51 and 6. The detector
counted every price TOUCHED. This replays the corpus through the real engine
with the level floor off, keeps every sweep it emits with its per-price split,
and reports how the emissions change under candidate floors.

Two gate sets, because the backfill question is historical:
  current  — production gates (span <= 5 ms, one print >= 50%, 2026-08-27)
  pre-0827 — the gates in force on 08-21 (span and concentration off)

    .venv/bin/python scripts/measurement/sweep_level_size.py --days 60 \\
        --out docs/measurement/2026-09-30-sweep-level-size.md

Regular session only (08:30-15:00 CT). Read-only over data/corpus.
"""
from __future__ import annotations

import argparse
import sys
from datetime import date, datetime, time
from pathlib import Path
from zoneinfo import ZoneInfo

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

import market.orderflow.engine as eng  # noqa: E402
from market.orderflow.replay import has_es_day  # noqa: E402
from market.orderflow.tradesource import iter_trades  # noqa: E402
from market.signals.orderflow import SweepPrint  # noqa: E402

CT = ZoneInfo("America/Chicago")
ABS_FLOORS = (0, 5, 10, 20, 30, 50)
SHARE_FLOORS = (0.0, 0.05, 0.10, 0.15, 0.20)


def corpus_days(limit: int) -> list[date]:
    root = REPO / "data" / "corpus"
    days = []
    for p in sorted(root.iterdir(), reverse=True):
        try:
            d = date.fromisoformat(p.name)
        except ValueError:
            continue
        if d.weekday() < 5 and has_es_day(d):
            days.append(d)
        if len(days) >= limit:
            break
    return sorted(days)


def sweeps_for(d: date, gates: str) -> list[SweepPrint]:
    eng.SWEEP_LEVEL_MIN_SIZE = 0
    eng.SWEEP_LEVEL_MIN_SHARE = 0.0
    if gates == "pre-0827":
        eng.SWEEP_MAX_SPAN_MS = 10**9
        eng.SWEEP_MIN_CONCENTRATION = 0.0
    else:
        from market.signals import orderflow_config as cfg
        eng.SWEEP_MAX_SPAN_MS = cfg.SWEEP_MAX_SPAN_MS
        eng.SWEEP_MIN_CONCENTRATION = cfg.SWEEP_MIN_CONCENTRATION
    start = datetime.combine(d, time(8, 30), CT)
    end = datetime.combine(d, time(15, 0), CT)
    e = eng.OrderflowEngine()
    out: list[SweepPrint] = []
    for t in iter_trades(d, start_ts=start, end_ts=end):
        out.extend(s for s in e.process(t) if isinstance(s, SweepPrint))
    out.extend(s for s in e.flush() if isinstance(s, SweepPrint))
    return out


def counted(s: SweepPrint, abs_floor: int, share: float) -> int:
    floor = max(abs_floor, share * s.total_size)
    return sum(1 for _, n in s.level_sizes if n >= floor)


def single_price_with_tail(s: SweepPrint) -> bool:
    """One price carries >= 80% of the run and every other price < 10%."""
    sizes = sorted((n for _, n in s.level_sizes), reverse=True)
    return sizes[0] >= 0.8 * s.total_size and all(n < 0.1 * s.total_size for n in sizes[1:])


def report(days: list[date], results: dict[str, list[tuple[date, SweepPrint]]]) -> str:
    lines = ["# Sweep level size — what each counted price carries [st-r6ni]", "",
             f"Replayed {len(days)} RTH sessions, {days[0]} to {days[-1]}, through "
             "market/orderflow/engine.py with the level floor off. Generated by "
             "`scripts/measurement/sweep_level_size.py`.", ""]
    for gates, rows in results.items():
        n = len(rows)
        per_day = n / len(days) if days else 0
        tails = sum(1 for _, s in rows if single_price_with_tail(s))
        lines += [f"## Gates: {gates}", "",
                  f"{n} sweeps ({per_day:.1f}/day). Single-price fills wearing a tail "
                  f"(one price >= 80%, every other < 10%): **{tails}** "
                  f"({(100 * tails / n) if n else 0:.0f}%).", ""]
        smallest = sorted(min(nn for _, nn in s.level_sizes) for _, s in rows)
        if smallest:
            q = lambda f: smallest[min(len(smallest) - 1, int(f * len(smallest)))]  # noqa: E731
            lines += [f"Smallest price in each sweep, contracts: median {q(0.5)}, "
                      f"p25 {q(0.25)}, p10 {q(0.10)}, min {smallest[0]}.", ""]
        lines += ["Sweeps still emitted (>= 3 counted prices) by floor — "
                  "rows absolute contracts, columns share of the run:", "",
                  "| abs \\ share | " + " | ".join(f"{int(s * 100)}%" for s in SHARE_FLOORS) + " |",
                  "|---|" + "---|" * len(SHARE_FLOORS)]
        for a in ABS_FLOORS:
            cells = [str(sum(1 for _, s in rows if counted(s, a, sh) >= eng.SWEEP_MIN_TICKS))
                     for sh in SHARE_FLOORS]
            lines.append(f"| {a} | " + " | ".join(cells) + " |")
        lines.append("")
        lines += ["Every sweep, per-price split (contracts in walk order):", "",
                  "| day | CT | dir | total | split | tail? |", "|---|---|---|---|---|---|"]
        for d, s in rows[:400]:
            ct = s.timestamp.astimezone(CT).strftime("%H:%M:%S")
            split = " / ".join(str(nn) for _, nn in s.level_sizes)
            lines.append(f"| {d} | {ct} | {s.direction} | {s.total_size} | {split} | "
                         f"{'yes' if single_price_with_tail(s) else ''} |")
        if len(rows) > 400:
            lines.append(f"| … | {len(rows) - 400} more | | | | |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--days", type=int, default=60)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args(argv)
    days = corpus_days(args.days)
    if not days:
        print("no corpus days with ES trades", file=sys.stderr)
        return 1
    results: dict[str, list[tuple[date, SweepPrint]]] = {"current": [], "pre-0827": []}
    for d in days:
        for gates in results:
            try:
                results[gates].extend((d, s) for s in sweeps_for(d, gates))
            except (FileNotFoundError, ValueError) as exc:
                print(f"{d}: skipped ({exc})", file=sys.stderr)
                break
        print(f"{d}: current {sum(1 for x, _ in results['current'] if x == d)}, "
              f"pre-0827 {sum(1 for x, _ in results['pre-0827'] if x == d)}", file=sys.stderr)
    text = report(days, results)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8")
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
