#!/bin/bash
# Reactive watchers for strader
# Generated by domain-factory
set -euo pipefail

INVOKE=/usr/local/bin/zgent-invoke

# position-change-alert (file_change)
inotifywait -m -e modify "/var/moo/strader/positions.jsonl" | while read; do
  $INVOKE strader greeks-analysis
done &

# risk-breach (skill_output)
# skill_output trigger for risk-limit-enforcement — handled by PostToolUse hook
# Condition: alert_if_breached == true

# discord-intel (channel_message)
tail -f "/var/moo/logs/dreader-narrative.jsonl" | jq -r 'select(capability == "discord-intel") | .content' | while read -r line; do
  $INVOKE strader entry-signal-evaluation --context "Incoming market intel from Discord. Evaluate for actionable trade setups. Cross-reference with current positions."
done &

echo "[watchers] All reactive watchers started for strader"
wait
