#!/bin/bash
# Strader session boot script
# Generated by domain-factory from strader domain profile
set -euo pipefail

SESSION="strader"

if sudo -u gtuser tmux has-session -t "${SESSION}" 2>/dev/null; then
  echo "[boot] Session ${SESSION} already exists, skipping creation"
  exit 0
fi

# Create session with cockpit pane
sudo -u gtuser tmux new-session -d -s "${SESSION}" -n main
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.0" @room_name "cockpit"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.0" @room_type "workspace"

# Split for positions pane
sudo -u gtuser tmux split-window -h -l 40% -t "${SESSION}:main"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.1" @room_name "positions"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.1" @room_type "display"
sudo -u gtuser tmux send-keys -t "${SESSION}:main.1" 'watch -n 30 cat /var/moo/strader/positions.txt' Enter

# Split for alerts pane
sudo -u gtuser tmux split-window -v -l 20% -t "${SESSION}:main"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.2" @room_name "alerts"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.2" @room_type "alert"

# Split for narrative pane
sudo -u gtuser tmux split-window -h  -t "${SESSION}:main"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.3" @room_name "narrative"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.3" @room_type "display"

# Split for log pane
sudo -u gtuser tmux split-window -v -l 15% -t "${SESSION}:main"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.4" @room_name "log"
sudo -u gtuser tmux set-option -p -t "${SESSION}:main.4" @room_type "log"

# Apply tiled layout
sudo -u gtuser tmux select-layout -t "${SESSION}:main" tiled

# Focus cockpit pane
sudo -u gtuser tmux select-pane -t "${SESSION}:main.0"

# Start reactive watchers
bash "$(dirname "$0")/strader-watchers.sh" &

echo "[boot] Session ${SESSION} created with 5 panes"
